// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package clocation;

@net.sf.jni4net.attributes.ClrType
public class Coordinate extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected Coordinate(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public Coordinate() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        clocation.Coordinate.__ctorCoordinate0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorCoordinate0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getLatitude();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setLatitude(double value);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getLongitude();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setLongitude(double value);
    
    @net.sf.jni4net.attributes.ClrMethod("()D")
    public native double getAccuracy();
    
    @net.sf.jni4net.attributes.ClrMethod("(D)V")
    public native void setAccuracy(double value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getLocationSource();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setLocationSource(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getCivicAddress();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setCivicAddress(java.lang.String value);
    
    public static system.Type typeof() {
        return clocation.Coordinate.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        clocation.Coordinate.staticType = staticType;
    }
    //</generated-proxy>
}
