// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package clocation;

@net.sf.jni4net.attributes.ClrType
public class LocationResponse extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected LocationResponse(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public LocationResponse() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        clocation.LocationResponse.__ctorLocationResponse0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorLocationResponse0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getCode();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setCode(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getDescription();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setDescription(java.lang.String value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LCLocation/Coordinate;")
    public native clocation.Coordinate getCoordinate();
    
    @net.sf.jni4net.attributes.ClrMethod("(LCLocation/Coordinate;)V")
    public native void setCoordinate(clocation.Coordinate value);
    
    public static system.Type typeof() {
        return clocation.LocationResponse.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        clocation.LocationResponse.staticType = staticType;
    }
    //</generated-proxy>
}
